### PR TITLE
WIP Hardware acceleration through WGL_NV_DX_interop

### PR DESCRIPTION
**Pull request by Eschryn**
To improve performance, the control should support WGL_NV_DX_interop. 
The control can alternatively use a D3DImage as source instead of an ImageSource and interop with DirectX directly to increase performance.

### CODE REVIEW

**Comment by MonoMaxMW** [comment]
Hello guys,
what is the current status on this.
Has someone found already a solution ?

Regards,
Max

**Comment by varon** [comment]
@MonoMaxMW Apparently there's some updates on this! Hopefully we can get this merged and working.

**Comment by mikau16** [comment]
Yes, would love to hear some updates or see some movement on this. Rather exciting!

**Comment by mikau16** [comment]
@Eschryn can we expect some updates on this soon? :)

**Comment by MonoMaxMW** [comment]
@mikau16 I've hacked something together if you would like to use it an implement it for this wpf control
https://github.com/MonoMaxMW/MonoMax.OpenGLWpfDemo/tree/master/MonoMax.WPFGLControl

**Comment by mikau16** [comment]
Thanks @MonoMaxMW. Does this use WGL_NV_DX_interop or some other type of hardware acceleration?

**Comment by MonoMaxMW** [comment]
Hello,

Yes it is using WGL_NV_DX_interop to render the OpenGL framebuffer texture attachment to an DirectX texture which is shown on the screen.

The only thing is that I’m using the SharpDX libraries for the DirectX context. We would need to crate this from scratch if it should work without the usage of said library.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Eschryn** [comment]
I also have something lying around but I seem to have a graphics card issue or some sort. You should come visit the OpenTK discord server.

**Comment by mikau16** [comment]
Love the responsiveness you guys! 👍 

@Eschryn any chance you'd be willing to share to see if it works on someone else's setup? I can contact you on Discord.

@MonoMaxMW , Thanks so much for sharing! Unfortunately the demo produces a blank WPF window for me, even though I have confirmed that WGL_ND_DX_interop is supported on my machine. I will open an issue under your project.

**Comment by varon** [comment]
FINALLY SOLVED! Huge thanks to @Eschryn  for his help in this.

Solved by and merged in #10 

3.0.0 includes full DX_interop support and has AMAZING performance.

**Comment by varon** [comment]
@MonoMaxMW  - Thanks for the example. Your work was also enormously helpful in finding out where our issue lay. Turns out it was the WGL bindings, which have been fixed in upstream OpenTK since discovery.

We also managed to fix the flickering issue and improve upon the performance of your example. We hope you get as much usage out of the new control implementation!

**Pull request closed without merging**
